name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      # Step 3: Add EC2 to known_hosts
      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 4: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to project directory
            cd /var/www/html/Laravel_HuLang

            # Fix ownership and permissions (assuming www-data is the web server user)
            sudo chown -R www-data:www-data /var/www/html/Laravel_HuLang
            sudo chmod -R 775 /var/www/html/Laravel_HuLang/storage
            sudo chmod -R 775 /var/www/html/Laravel_HuLang/bootstrap/cache

            # Mark directory as safe for Git
            git config --global --add safe.directory /var/www/html/Laravel_HuLang

            # Run Laravel deployment steps as www-data user
            sudo -u www-data php artisan down || true
            git fetch origin
            git reset --hard origin/main

            # Clear vendor directory and reinstall dependencies
            rm -rf vendor/*
            sudo -u www-data composer install --no-dev --optimize-autoloader

            # Run migrations and cache commands
            sudo -u www-data php artisan migrate --force
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache

            # Reload and restart Apache
            sudo systemctl daemon-reload
            sudo systemctl restart apache2

            # Bring application back up
            sudo -u www-data php artisan up
          EOF